sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ankiwadhwa2/reactapp-dev -f Dockerfile.dev .

script:
  - docker run -e CI=true ankiwadhwa2/reactapp-dev npm run test -- --coverage
